# CUDA
cuda_devices: '0'

# dataset
dataset:
  data_root: 'dataset/ModelNet10_processed'
  augment_data: false
  max_faces: 1000

# model
load_model: 'MeshNet_ModelNet10_150e_bs128_lr6e-4.pkl'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'  # Concat/Max/Average
  mask_ratio: 0.95
  dropout: 0.5
  num_classes: 10

# test config
batch_size: 64
retrieval_on: true